
all:
	pdflatex Dynamics_Memristor_Networks.tex

clean:
	rm Dynamics_Memristor_Networks.pdf
	rm Dynamics_Memristor_Networks.toc
	rm Dynamics_Memristor_Networks.aux
	rm Dynamics_Memristor_Networks.out
	rm Dynamics_Memristor_Networks.nav
	rm Dynamics_Memristor_Networks.log
	rm Dynamics_Memristor_Networks.snm
